import os
from PIL import Image, ImageFilter, ImageEnhance, ImageDraw
import numpy as np

# Background scene
bg_path = r"C:\Users\Wusch\.gemini\antigravity-ide\brain\578ab548-d975-4692-bc32-38b3e2339992\clean_set_ritual_box_1786923237084.jpg"
bg = Image.open(bg_path).convert('RGBA')

# Cutouts generated by rembg
cut_spray = Image.open('scratch/rembg_oficiales/spray_cut.png').convert('RGBA')
cut_mikado = Image.open('scratch/rembg_oficiales/mikado_cut.png').convert('RGBA')
cut_recarga = Image.open('scratch/rembg_oficiales/recarga_cut.png').convert('RGBA')

# Accurate physical scaling on the travertine tray
# Home Spray ~ 440px
h_spray = 440
w_spray = int(cut_spray.width * (h_spray / cut_spray.height))
r_spr = cut_spray.resize((w_spray, h_spray), Image.Resampling.LANCZOS)

# Mikado (glass body ~180px, total height with sticks ~ 390px)
h_mik = 390
w_mik = int(cut_mikado.width * (h_mik / cut_mikado.height))
r_mik = cut_mikado.resize((w_mik, h_mik), Image.Resampling.LANCZOS)

# Recarga Eco ~ 420px
h_rec = 420
w_rec = int(cut_recarga.width * (h_rec / cut_recarga.height))
r_rec = cut_recarga.resize((w_rec, h_rec), Image.Resampling.LANCZOS)

# Soft natural contact shadow on the travertine stone (oval blurred)
def make_contact_shadow(w, h=16, blur=4, opacity=0.75):
    s = Image.new('RGBA', (w + 40, h + 30), (0, 0, 0, 0))
    d = ImageDraw.Draw(s)
    # Oval shadow
    d.ellipse((20, 15, 20 + w, 15 + h), fill=(25, 20, 15, int(255 * opacity)))
    return s.filter(ImageFilter.GaussianBlur(blur))

def make_directional_cast(img, blur=12, opacity=0.35):
    a = img.split()[-1]
    s_mask = a.point(lambda p: int(p * opacity))
    s = Image.new('RGBA', img.size, (28, 22, 18, 255))
    s.putalpha(s_mask)
    return s.filter(ImageFilter.GaussianBlur(blur))

# Staggered positioning inside the tray:
# The travertine tray floor is around y=730..770
# Tray left: x=120, Tray right: x=500
pos_spr = (125, 480)    # Base at y=480+440=920 -> wait, tray floor is at y=760
# Let's adjust y so bottle bottoms sit at y=760 (tray floor)
# Spray height 440 -> y = 760 - 440 = 320 ? No, let's check tray floor y coordinate in bg image!
